yatube/about/urls.py
from django.urls import path
from .views import AboutTechView, AboutAuthorView

app_name = 'about'

urlpatterns = [
    path('author/', AboutAuthorView.as_view(), name='author'),
    path('tech/', AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'post'

urlpatterns = [
    path('', views.index, name='main'),
    path('group/<slug:slug>/', views.group_posts, name='group'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('create/', views.post_create, name='create'),
]

yatube/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from . import views

app_name = 'users'

urlpatterns = [
    path('logout/',
         LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/',
         LoginView.as_view(template_name='users/login.html'),
         name='login'),

]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='post')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

User = get_user_model()


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст публикации',
    )
    pub_date = models.DateTimeField(
        verbose_name='Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='posts'
    )
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name='Группа',
    )

    class Meta:
        ordering = ['pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Название группы',
        blank=True
    )
    slug = models.SlugField(
        verbose_name='URL',
        unique=True
    )
    description = models.TextField(
        verbose_name='Описание',
        blank=True
    )

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('group', kwargs={'slug': self.slug})

yatube/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['group'].empty_label = 'Категория не выбрана'

    class Meta:
        model = Post
        fields = ['text', 'group']
        label = {
            'text': 'Содержание',
            'group': 'Группа',
        }
        help_text = {
            'text': 'Текст поста',
            'group': 'Группа,к которой будет относиться пост',
        }

yatube/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['just_title'] = 'О сайте'
        return context


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['just_title'] = 'Технологии'
        return context

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect

from .forms import PostForm
from .models import Post, User, Group

AMOUNT_POST = 10


def index(request):
    template = 'posts/index.html'
    title = 'Последние обновления на сайте'
    post_list = Post.objects.all().order_by('-pub_date')
    paginator = Paginator(post_list, AMOUNT_POST)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'title': title,
    }
    return render(request, template, context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = author.posts.all()
    paginator = Paginator(post_list, AMOUNT_POST)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    counter_posts = author.posts.count()
    context = {
        'author': author,
        'page_obj': page_obj,
        'counter_posts': counter_posts,

    }
    template = 'posts/profile.html'
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    title = 'Записи сообщества'
    group = get_object_or_404(Group, slug=slug)
    get_posts = Post.objects.filter(group=group)
    posts = get_posts.order_by('-pub_date')[:AMOUNT_POST]
    paginator = Paginator(posts, AMOUNT_POST)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'title': title,
        'group': group,
        'posts': posts,
    }
    return render(request, template, context)


# Исправлено в шаблоне post_detail
def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    username_obj = User.objects.get(username=post.author)
    posts_counter = username_obj.posts.count()
    template = 'posts/post_detail.html'
    title = 'Подробная информация'
    context = {
        'title': title,
        'post': post,
        'posts_counter': posts_counter
    }
    return render(request, template, context)


@login_required
def post_create(request):
    form = PostForm(request.POST)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('post:profile', request.user)
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(request.POST, instance=post)
    if post.author != request.user:
        return redirect('post:post_detail', post_id=post_id)
    if form.is_valid():
        post.save()
        return redirect('post:post_detail', post.pk,)
    is_edit = True
    context = {'form': form, 'is_edit': is_edit}
    return render(request, 'posts/create_post.html', context)

# Второй вариант реализации подробнее и мне понятнее,чем первый.
# @login_required
# def post_edit(request, post_id):
#     post = get_object_or_404(Post, pk=post_id)
#     if post.author != request.user:
#         return redirect('post:post_detail', post_id=post_id)
#     elif request.method == 'POST':
#         form = PostForm(request.POST, instance=post)
#         form.save()
#         return redirect('post:post_detail', post_id=post_id)
#     else:
#         form = PostForm(initial={'group': post.group, 'text': post.text})
#     is_edit = True
#     context = {'form': form, 'is_edit': is_edit, 'post': post}
#     return render(request, 'posts/create_post.html', context)

yatube/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('post:main')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<h1>Привет, я автор</h1>
<p>
  Тут что-то будет такое-эдакое
</p>
{% endblock %}

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
{% comment %} Колонки с отступом сверху и снизу {% endcomment %}
<div class="row">
  <h1>Вот что я умею</h1>
  {% comment %}
    Боковой блок со списком технологий 
    Займет всю ширину блока на мобильном
    и 25% при размерах экрана ≥768px
  {% endcomment %}
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
    </ul>
  </aside>
  {% comment %}
    Статья  
    Займет всю ширину блока на мобильном
    и 75% при размерах экрана ≥768px
  {% endcomment %}
  <article class="col-12 col-md-9">
    <p>Текст страницы "Технологии"</p>
  </article>
</div>
{% endblock %} 

yatube/templates/base.html
<!DOCTYPE html>
  {% load static %}
  <html lang="ru">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
      <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
      <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
      <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
      <meta name="msapplication-TileColor" content="#000">
      <meta name="theme-color" content="#ffffff">
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
      <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
      {% include 'includes/header.html' %}
      <main>
        <div class="container">
          {% block content %}
          {% endblock %}
        </div>
      </main>

      {% include 'includes/footer.html' %}
    </body>
  </html>

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright  <span style="color:red">Ya</span>tube</p>
</footer>

yatube/templates/includes/header.html
{% load static %}
<header>
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <li class="nav-item" style='list-style-type: none'>
        <div class="container">
            <a class="navbar-brand" href="{% url 'post:main' %}">
                <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
                <span style="color:red">Ya</span>tube</a>
            </a>
        </div>
        </li>
                    {% with request.resolver_match.view_name as view_name %}
         <ul class="nav nav-pills">
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" href="{% url 'about:author' %}">Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}" href="{% url 'about:tech' %}">Технологии</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'post:create' %}active{% endif %}" href="{% url 'post:create' %}">Новая запись</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'password_change' %}active{% endif %}" href="{% url 'password_change' %}">Изменить пароль</a>
        </li>
            {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'logout' %}active{% endif %}" href="{% url 'logout' %}">Выйти</a>
        </li>
        <li class="nav-item">
          Пользователь: {{user.username}}
        <li>
             {% else %}
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'users:signup' %}active{% endif %}" href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'users:login' %}active{% endif %}" href="{% url 'users:login' %}">Войти</a>
        </li>
        {% endif %}
      </ul>
    </nav>
    {% endwith %}
</header>

yatube/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
    <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
        Предыдущая
      </a>
    </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
    {% if page_obj.number == i %}
    <li class="page-item active">
      <span class="page-link">{{ i }}</span>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ i }}">{{ i }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}">
        Следующая
      </a>
    </li>
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
        Последняя
      </a>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% load user_filters %}
{% block title %}
{% if is_edit %}Редактировать пост{% else %}Новый пост{% endif %}
{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %} Редактировать пост {% else %} Новый пост {% endif %}
        </div>
        <div class="card-body">
          {% if form.errors %}
          {% for error in field.errors %}
          <div class="alert alert-danger">
            {{ error }}
          </div>
          {% endfor %}
          {% for error in form.non_field_errors %}
          <div class="alert alert-danger">
            {{ error }}
          </div>
          {% endfor %}
          {% endif %}
          <form method="post">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group row my-3 p-3">
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                {% if field.field.required %}
                <span class="required text-danger">*</span>
                {% endif %}
              </label>
              {{ field|addclass:"form-control" }}
              {% if field.help_text %}
              <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                {{ field.help_text }}
              </small>
              {% endif %}
            </div>
            {% endfor %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %} Сохранить {% else %} Добавить {% endif %}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}Посты групы {{ group.title }} {% endblock %}
{% block content %}
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>
  {% for post in posts %}
    <ul>
      <li>Автор: {{ post.author.get_full_name }}</li>
      <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
    </ul>
    <p>{{ post.text }}</p>
      {% if not forloop.last %}
        <hr>
      {% endif %}
  {% endfor %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}Главная  {% endblock %}
{% block content %}
  {% for post in page_obj %}
    <ul>
      <li>Автор: {{ post.author.get_full_name }}</li>
      <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
    </ul>
    <p>{{ post.text }}</p>
      {% if post.group %}
        <a href="{% url 'post:group' post.group.slug %}">все записи группы</a>
      {% endif %}
      {% if not forloop.last %}
        <hr>
      {% endif %}
  {% endfor %}
  {% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %} Пост {{ post.text|truncatechars:15 }} {% endblock %}
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
        <li class="list-group-item">
          {% if post.group %}
            Группа: {{ post.group.title}}
        </li>
        <li class="list-group-item">
          <a href="{% url 'post:group' post.group.slug %}">все записи группы</a>
        </li>
         {% endif %}
        <li class="list-group-item">
          Автор: {{ post.author}}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора: <span> {{ posts_counter }} </span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'post:profile' post.author %}">Все посты пользователя</a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      <p>{{ post.text }}</p>
      {% if request.user == post.author %}
        <a href="{% url 'post:post_edit' post.id %}">Редактировать пост</a>
      {% endif %}
    </article>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %} Все посты пользователя {{ author }} {% endblock %}
{% block content %}
  {% for post in page_obj %}
  <main>
    <div class="container py-5">
      <h1>Все посты пользователя {{ author }}</h1>
      <h3>Всего постов: {{ counter_posts }} </h3>
      <article>
        <ul>
          <li>Автор: {{ author }}
            <a href="{% url 'post:profile' author %}">Все посты пользователя</a>
          </li>
          <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
        </ul>
        <p>{{ post.text }}</p>
        <a href="{% url 'post:post_detail' post.pk %}">Подробная информация </a>
      </article>
      {% if post.group %}
        <a href="{% url 'post:group' post.group.slug %}">Все записи группы</a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
       {% endfor %}
        {% include 'includes/paginator.html' %}
    </div>
  </main>

{% endblock %}

yatube/templates/users/logged_out.html
{% extends "base.html" %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Вы вышли из системы</div>
      <div class="card-body">
        <p>Вы вышли из своей учётной записи. Ждём вас снова!</p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Войти на сайт</div>
      <div class="card-body">
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
          Имя пользователя и пароль не совпадают. Введите правильные данные.
        </div>
        {% endif %}
        <div class="alert alert-info" role="alert">
          Пожалуйста, авторизуйтесь.
        </div>
        <form method="post" action="{% url 'login' %}">
          {% csrf_token %}
          {% for field in form %}
          <div class="form-group row">
            <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">
              {{ field.label }}</label>
            <div class="col-md-6">
              {{ field|addclass:"form-control" }}
            </div>
          </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <a href="{% url 'password_reset' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/password_change.html
{% extends "base.html" %}
{% block title %}Сменить пароль{% endblock %}
{% block content %}
{% load user_filters %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Изменить пароль</div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          {% for field in form %}
          <div class="form-group row">
            <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">
              {{ field.label }}</label>
            <div class="col-md-6">
              {{ field|addclass:"form-control" }}
            </div>
          </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Изменить пароль
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/password_change_done.html
{% extends "base.html" %}
{% block title %}Пароль изменён{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Пароль изменён</div>
      <div class="card-body">
        <p>Пароль изменён успешно</p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/password_done.html
{% extends "base.html" %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Сброс пароля прошёл успешно</div>
      <div class="card-body">
        <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля.</p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/password_reset.html
{% extends "base.html" %}
{% block title %}Забыли пароль?{% endblock %}
{% block content %}
{% load user_filters %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы
        регистрировались
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          {% for field in form %}
          <div class="form-group row">
            <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">
              {{ field.label }}</label>
            <div class="col-md-6">
              {{ field|addclass:"form-control" }}
            </div>
          </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Сбросить пароль
            </button>
          </div>
        </form>

      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block content %}
{% load user_filters %}
{% if validlink %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Введите новый пароль</div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          {% for field in form %}
          <div class="form-group row">
            <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label
              }}</label>
            <div class="col-md-6">
              {{ field|addclass:"form-control" }}
            </div>
          </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Назначить новый пароль
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% else %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Ошибка</div>
      <div class="card-body">
        <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
      </div>
    </div>
  </div>
</div>
{% endif %}
{% endblock %}

yatube/templates/users/password_reset_form.html
{% extends "base.html" %}
{% block title %}Забыли пароль?{% endblock %}
{% block content %}
{% load user_filters %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы
        регистрировались
      </div>
      <div class="card-body">

        <form method="post">
          {% csrf_token %}

          {% for field in form %}
          <div class="form-group row">
            <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label
              }}</label>
            <div class="col-md-6">
              {{ field|addclass:"form-control" }}
            </div>
          </div>
          {% endfor %}

          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Сбросить пароль
            </button>
          </div>
        </form>

      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
{% load user_filters %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Зарегистрироваться</div>
      <div class="card-body">
        {% for error in form.errors %}
        <div class="alert alert-danger" role="alert">
          {{ error }}
        </div>
        {% endfor %}
        <form method="post">
          {% csrf_token %}
          {% for field in form %}
          <div class="form-group row">
            <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">
              {{ field.label }}
              {% if field.field.required %}
              <span class="required">*</span>{% endif %}</label>
            <div class="col-md-6">
              {{ field|addclass:"form-control" }}
              {% if field.help_text %}
              <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
              {% endif %}
            </div>
          </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Зарегистрироваться
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}